_target_: gentle_grasp.model.static_sound_aware.SoundAwareModel
visual_embed: null
touch_embed_thumb: null
touch_embed_middle: null
action_embed_motion: null
action_embed_pose: null
# action_embed_motion:
#   _target_: gentle_grasp.model.static_sound_aware.ActionEmbeddingMLP
#   input_dim: 4
#   hidden_dim: 64
#   embedding_dim: 64
#   dropout: 0.25
# action_embed_pose:
#   _target_: gentle_grasp.model.static_sound_aware.ActionEmbeddingMLP
#   input_dim: 16
#   hidden_dim: 64
#   embedding_dim: 64
#   dropout: 0.25
sound_embdedding:
  _target_: gentle_grasp.model.static_sound_aware.AudioEmbeddingCNN
  embedding_dim: 64
final_classifier:
  _target_: gentle_grasp.model.static_sound_aware.FinalClassifierMLP
  _partial_: true
  hidden_dim: 1024
  output_dim: 1
  dropout: 0.25