_target_: gentle_grasp.model.static_sound_aware.StaticSoundAwareModel
dropout_sensory: 0.35
dropout_action: 0.35
dropout_final: 0.35
action_hidden_dim: 64
action_embedding_dim: 64
sound_embedding_dim: 64
final_hidden_dim: 1024