image:
  pre:
    - _target_: torchvision.transforms.v2.transforms.Resize
      size: [256, 256]

  augmentations:
    - _target_: torchvision.transforms.v2.transforms.RandomCrop
      size: [224, 224]

  post:
    - _target_: torchvision.transforms.v2.transforms.ToTensor
    - _target_: torchvision.transforms.v2.transforms.Normalize
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]

sensor:
  pre:
    - _target_: torchvision.transforms.v2.transforms.Resize
      size: [256, 256]

  augmentations:
    - _target_: torchvision.transforms.v2.transforms.RandomCrop
      size: [224, 224]

  post:
    - _target_: torchvision.transforms.v2.transforms.ToTensor
    - _target_: torchvision.transforms.v2.transforms.Normalize
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]

audio: ...
